export default {
  REQUEST_MOVIE_LIST: 'REQUEST_MOVIE_LIST',
  RESPONSE_MOVIE_LIST: 'RESPONSE_MOVIE_LIST',
  REQUEST_MOVIE_DETAILS: 'REQUEST_MOVIE_DETAILS',
  RESPONSE_MOVIE_DETAILS: 'RESPONSE_MOVIE_DETAILS',
  SEARCH_QUERY_CHANGED: 'SEARCH_QUERY_CHANGED'
};