export const REQUEST_MOVIE_LIST = 'REQUEST_MOVIE_LIST';
export const RESPONSE_MOVIE_LIST = 'RESPONSE_MOVIE_LIST';
export const REQUEST_MOVIE_DETAILS = 'REQUEST_MOVIE_DETAILS';
export const RESPONSE_MOVIE_DETAILS = 'RESPONSE_MOVIE_DETAILS';